longitudinal_controller:
  ros__parameters:
    look_ahead_distance: 2.0       # in meters
    timer_duration_msec: 100.0       # in milliseconds
    csv_file_path: "/data/parking_lot_trajectory_traffic_smoother_test_1.csv"
    control_mode: 1
